### ISSUE TITLE
[Feature] tab play function

### ISSUE THREAD

**Issue by limetree06** [mipsSimulatorUNIST/reactGUI#11]
## Description
이슈에 대한 설명을 작성해주세요
어셈블러 play, reset 기능 제작
<br>
## Todo
- [ ] assemble mapping table npm 으로 부터 받아오기
- [x] reset, play 아이콘 추가
- [x] 버튼 추가 + 버튼 눌렀을 시 line number 변화
- [x] line number Tab text tab에 넘겨주기
- [x] 확인

<br>

## ETC
기타 참고 사항이 있으면 작성해주세요.
