### ISSUE TITLE
[Feature] assemblePanelHovering

### ISSUE THREAD

**Issue by limetree06** [mipsSimulatorUNIST/reactGUI#17]
## Description
이슈에 대한 설명을 작성해주세요

<br>

## Todo
- [x] 바이너리 panel 선택했을때 UI 문제 
- [x] 바이너리 Panel 선택해고 assembly도 같이 변화게
- [x] 함수에 맵핑된 PC 값, data. text.에 맵핑된 PC 값에 따라서 바이너리 패널 부분 하이라이트
- [x] hovering시 위에 설명 뜨게

<br>

## ETC
기타 참고 사항이 있으면 작성해주세요.
