### ISSUE TITLE
[Feature] GUI README 추가

### ISSUE THREAD

**Issue by bams11** [mipsSimulatorUNIST/reactGUI#35]
## Description
GUI에 대한 README 작성 
<br>
## Todo
- [x] 간단한 프로젝트 설명
- [x] simulator 기능
- [x] 프로젝트 목적
- [x] 간단한 사용방법 (+ 사진, 움짤)
- [x] 사용한 npm library - mips-simulator-js 에 대한 간단한 설명과 링크

<br>

## ETC
기타 참고 사항이 있으면 작성해주세요.
![assembler1](https://user-images.githubusercontent.com/64965613/224534333-5fdbef0b-f8e3-43a4-b316-bfeb63330aa3.gif)
![assembler2](https://user-images.githubusercontent.com/64965613/224534335-64ae7e13-d9e7-405f-9b69-0b25d869449d.gif)
![simulator1](https://user-images.githubusercontent.com/64965613/224534337-7f118634-cfb6-475c-bf94-61c6714358a2.gif)
